name: Build and Deploy Website

on: 
  workflow_dispatch:
  push:
    branches: main

# Sets permissions of the GITHUB_TOKEN to allow pushing to branches
permissions:
  contents: write
  
# Allow one concurrent deployment
concurrency:
  group: "production-deploy"
  cancel-in-progress: true
  
env:
  listPublishDirectory: Website
  pathToCi: ci

jobs:
  
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4 # check out this repo
      - uses: actions/checkout@v4 # check out automation repo
        with:
          repository: vrchat-community/package-list-action
          path: ${{env.pathToCi}}
          clean: false # otherwise the local repo will no longer be checked out
          
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{env.pathToCi}}/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          
      - name: Build Package Version Listing
        run: ${{env.pathToCi}}/build.cmd BuildMultiPackageListing --root ${{env.pathToCi}} --list-publish-directory $GITHUB_WORKSPACE/${{env.listPublishDirectory}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy data files to Website
        run: |
          cp -r data/* Website/data/
          cp source.json Website/
          
      - name: Deploy to production branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Website
          publish_branch: production
          force_orphan: true
